Complete Project
badger-99/space-travelers-hub pull request #62
Opened 2023-08-09 10:17 UTC by badger-99

This PR proposes moving the completed **Space Traveler's Hub** project by @badger-99 and @majdalkilany to the `master` branch. The project includes the following features:
- Separate pages for Rockets, Missions. and the user's profile.
- The ability reserve a rocket or to cancel your reservation for for any of the rockets.
- The ability to join or leave a mission.
- A **My Profile** page that keeps track of missions you have joined. and rockets you have reserved.
- Dynamic elements that are rendered depending on the reservation status of a rocket or a mission.

2023-08-09 10:57 UTC, usorfaitheloho requested changes
> Hi @badger-99  and @majdalkilany  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * Used REACT REDUX ✔️
> * Descriptive pull request ✔️
> * Used REACT ROUTER✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-09 10:57 UTC, usorfaitheloho commented on README.md
> +It correctly bundles React in production mode and optimizes the build for the best performance.
You did well with the group capstone project, kindly note that you are expected to use the Microverse template for your README file so as to include all the details needed for your project. please use [this](https://github.com/microverseinc/readme-template) link 😄

2023-08-09 10:57 UTC, usorfaitheloho commented on README.old.md
> +# space-travelers-hub
Kindly delete this README file as it is not useful and shouldn't be in your project directory 👍

2023-08-09 10:57 UTC, usorfaitheloho commented on src/setupTests.js
> +import '@testing-library/jest-dom';
Please note that as part of the requirement, you are expected to write Tests for your project 👍 

![image](https://github.com/badger-99/space-travelers-hub/assets/20537712/eeed12a8-bb33-4bcd-b28a-916bdd991335)

2023-08-10 02:05 UTC, franclobo approved these changes
Hi @badger-99 and @majdalkilany, 

# STATUS: APPROVED 😃 

![leonardo-dicaprio-leo-dicaprio](https://github.com/badger-99/space-travelers-hub/assets/58642949/4c6ce925-65c7-486c-be5e-bd2c3edeca8a)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights

- Use React components ✔️ 
- Connect React and Redux ✔️ 
- All tests passed ✔️ 

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-08-10 02:06 UTC, merged